image: proboci/ubuntu-14.04-lamp:7.0-beta
assets:
  - wp-engine-482.sql.gz
steps:
  - name: Check wp-cli.
    plugin: Script
    script:
      - wp --info --allow-root
  - name: Setting up WP on Probo
    plugin: WordPressApp
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    database: 'wp-engine-482.sql.gz'
    databaseName: 'wp_zivtech'
    databaseGzipped: true
  - name: Create admin user.
    plugin: Script
    script:
      - wp user create admin dev@probo.ci --role=administrator --allow-root
  - name: Import wp-cfm configs.
    plugin: Script
    script:
      - wp config pull active_plugins --allow-root
      - wp config pull wordpress_seo --allow-root
