assets:
  - wpe.sql
  steps:
  - name: Setting up WP on Probo
    plugin: WordPressApp
    database: wpe.sql
    databaseName: wp_zivtech
    databaseGzipped: false
    subDirectory: code
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
  - name: Flush the cache
    plugin: WordPressApp
    flushCaches: true
