assets:
  - wpe.sql
  steps:
  - name: Site setup
    plugin: WordPressApp
    database: wpe.sql
    databaseName: wp_zivtech
    databaseGzipped: true
    subDirectory: code
    devDomain: zivtech.wpengine.com
    devHome: zivtech.wpengine.com
  - name: Flush the cache
    plugin: WordPressApp
    flushCaches: true
  - script: |
        curl $BUILD_DOMAIN
        curl --header 'x-api-key: 0f8ce8c48323a0f933af9a277877e6df' --request POST 'https://backtrac.io/api/project/59156/compare_custom' --data '{"url1":"https:\/\/zivtech.wpengine.com","sn1_name":"WP Live Site","url2":"'"$BUILD_DOMAIN"'","sn2_name":"WP Engine Probo Build","diff_name":"Live vs Probo"}'

