image: proboci/ubuntu-14.04-lamp:7.0-beta
assets:
  - wp-engine-482.sql.gz
steps:
  - name: Setting up WP on Probo
    plugin: WordPressApp
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    database: 'wp-engine-482.sql.gz'
    databaseName: 'wp_zivtech'
    databaseGzipped: true
    subDirectory: 'docroot'
