assets:
  - wpe.sql
steps:
  - name: Setting up WP on Probo
    plugin: WordPressApp
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    database: 'wpe.sql'
    databaseName: 'wp_zivtech'
    databaseGzipped: false
    subDirectory: 'code'
