assets:
  - wpe.sql
  steps:
  - name: Site setup
    plugin: WordPressApp
    database: wpe.sql
    databaseName: wp_zivtech
    databaseGzipped: true
    subDirectory: code
    devDomain: zivtech.wpengine.com
    devHome: zivtech.wpengine.com
  - name: Flush the cache
    plugin: WordPressApp
    flushCaches: true
