image: proboci/ubuntu-14.04-lamp:7.0-beta
assets:
  - wp-engine-482.sql.gz
steps:
  - name: Check wp-cli.
    plugin: Script
    script:
      - wp --info --allow-root
  - name: Setting up WP on Probo
    plugin: WordPressApp
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    database: 'wp-engine-482.sql.gz'
    databaseName: 'wp_zivtech'
    databaseGzipped: true
    subDirectory: 'docroot'
  - name: Import wp-cfm configs.
    plugin: Script
    script:
      - wp config pull active_plugins --allow-root
      - wp config pull wordpress_seo --allow-root
  - name: Clear WP cache.
    plugin: Script
    script:
      - wp cache flush --allow-root
  - name: Create admin user.
    plugin: Script
    script:
      - wp user create admin dev@probo.ci --role=administrator --allow-root
  - name: Run visual comparision to test via backtrac.io
    plugin: Script
    script: |
      curl --header 'x-api-key: 0f8ce8c48323a0f933af9a277877e6df' --request POST https://backtrac.io/api/project/78441/compare_custom --data '{"url1":"https:\/\/zivtech.wpengine.com","sn1_name":"Prod","url2":"'"$BUILD_DOMAIN"'","sn2_name":"Probo ","diff_name":"Prod vs Probo"}'
