image: proboci/ubuntu-14.04-lamp:7.0-beta
assets:
  - wp-engine-482.sql.gz
  - credentials.sh
steps:
  - name: Check wp-cli.
    plugin: Script
    script:
      - wp --info --allow-root
  - name: Setting up WP on Probo
    plugin: WordPressApp
    devDomain: 'http://zivtech.wpengine.com'
    devHome: 'http://zivtech.wpengine.com'
    database: 'wp-engine-482.sql.gz'
    databaseName: 'wp_zivtech'
    databaseGzipped: true
    subDirectory: 'docroot'
  - name: Import wp-cfm configs.
    plugin: Script
    script:
      - wp config pull active_plugins --allow-root
      - wp config pull wordpress_seo --allow-root
  - name: Clear WP cache.
    plugin: Script
    script:
      - wp cache flush --allow-root
  - name: Create admin user.
    plugin: Script
    script:
      - wp user create admin dev@probo.ci --role=administrator --allow-root
  - name: Run visual comparision to test via Backtrac.io and comment in Jira
    plugin: Script
    script: |
      echo '{"body": "Probo build at ' $BUILD_DOMAIN  >> comment.json
      echo ' and visual test at https://backtrac.io/node' >> comment.json
      curl --header 'x-api-key: 0f8ce8c48323a0f933af9a277877e6df' --request POST https://backtrac.io/api/project/78441/compare_custom --data '{"url1":"https://zivtech.wpengine.com","sn1_name":"Prod","url2":"'"$BUILD_DOMAIN"'","sn2_name":"Probo ","diff_name":"Prod vs Probo"}' | rev | awk -F , '{print $2}' | rev | awk -F \\ '{print $5 $6}' | tr -d '\"' >> comment.json
      echo '"}' >> comment.json
      source $ASSET_DIR/credentials.sh
      BRANCH_NAME=$(echo $BRANCH_NAME | awk '{match($0,"([aA-zZ]+)-([0-9]+)")} {print substr($0,RSTART,RLENGTH)}')
      curl -D- -u $JIRA_NAME:$JIRA_PASS -X POST --data @comment.json -H "Content-Type: application/json" https://jira.zivtech.com/rest/api/2/issue/$BRANCH_NAME/comment
